[package]
name = "edgedns"
version = "0.2.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[features]
webservice = ["hyper", "prometheus"]

default = ["webservice"]

[dependencies]
env_logger = "*"
log = {version = "*", features = ["nightly"]}
rand = "*"
siphasher = "*"
slab = "~0.3.0"
toml = "*"

hyper = {version="*", optional = true, default-features = false, features = ["nightly"]}
clippy = {version = "*", optional = true}

[dependencies.clockpro-cache]
git = "https://github.com/jedisct1/rust-clockpro-cache.git"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[dependencies.clap]
git = "https://github.com/kbknapp/clap-rs.git"
features = ["nightly"]

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[dependencies.nix]
git = "https://github.com/carllerche/nix-rust.git"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
default-features = false
features = ["nightly"]
optional = true

[profile.dev]
codegen-units = 4
panic = "unwind"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
