[package]
name = "edgedns"
version = "0.2.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[features]
webservice = ["hyper"]
nightly = ["clap/nightly", "hyper/nightly", "log/nightly", "prometheus/nightly"]

default = ["nightly", "webservice"]

[dependencies]
clap = {version = "*"}
clippy = {version = "*", optional = true}
clockpro-cache = "*"
env_logger = "*"
hyper = {version = "*", optional = true, default-features = false}
log = {version = "*"}
nix = "~0.7.0"
privdrop = "*"
prometheus = {version = "*", default-features = false}
rand = "*"
siphasher = "*"
slab = "*"
toml = "*"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[profile.dev]
codegen-units = 4
panic = "unwind"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
