[package]
name = "edgedns"
version = "0.2.2"
authors = ["Frank Denis <github@pureftpd.org>"]

[features]
webservice = ["hyper"]
nightly = ["clap/nightly", "hyper/nightly", "log/nightly", "prometheus/nightly", "coarsetime/nightly"]

default = ["nightly", "webservice"]

[dependencies]
bpf = "*"
clap = "*"
clippy = {version = "*", optional = true}
clockpro-cache = "*"
coarsetime = "*"
env_logger = "*"
hyper = {version = "*", optional = true, default-features = false}
jumphash = "*"
log = "*"
nix = "~0.7.0"
privdrop = "*"
prometheus = {version = "*", default-features = false}
rand = "*"
siphasher = "*"
socket-priority = "*"
slab = "*"
toml = "*"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"
rev = "53d1c788e07cb5c52044e6a8929f9d436876fdb6"

[dependencies.framestream]
git = "https://github.com/jedisct1/rust-framestream"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[dependencies.dnstap]
git = "https://github.com/jedisct1/rust-dnstap"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
