[package]
name = "edgedns"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[features]
webservice = ["civet", "conduit", "conduit-middleware", "conduit-router"]

[dependencies]
bytes = "*"
env_logger = "*"
log = "*"
rand = "*"
rustc-serialize = "*"
slab = "*"

[dependencies.civet]
version = "*"
optional = true

[dependencies.conduit]
version = "*"
optional = true

[dependencies.conduit-middleware]
version = "*"
optional = true

[dependencies.conduit-router]
version = "*"
optional = true

[dependencies.arc-cache]
git = "https://github.com/jedisct1/rust-arc-cache.git"

[dependencies.clap]
git = "https://github.com/kbknapp/clap-rs.git"

[dependencies.mio]
git = "https://github.com/jedisct1/mio.git"
branch = "mio_sender_clone"

[dependencies.nix]
git = "https://github.com/carllerche/nix-rust.git"

[profile.dev]
codegen-units = 4

[profile.release]
lto = true
