[package]
name = "edgedns"
version = "0.3.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[features]
webservice = ["libedgedns/webservice"]
nightly = ["libedgedns/nightly", "clap/nightly", "log/nightly"]

default = ["nightly", "webservice"]

[dependencies.libedgedns]
path = "src/libedgedns"

[dependencies]
clap = "*"
clippy = {version = "*", optional = true}
env_logger = "*"
log = "*"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
